"""add fiscal_start_month and update cycle_type

Revision ID: 9adbd83704ed
Revises: 3c88fdd7d5ea
Create Date: 2026-04-15 12:19:48.008249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9adbd83704ed'
down_revision: Union[str, None] = '3c88fdd7d5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('fiscal_start_month', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'fiscal_start_month')
    # ### end Alembic commands ###
