"""add_goal_access_control_columns

Revision ID: 9c28aac63a56
Revises: 9adbd83704ed
Create Date: 2026-04-16 11:59:06.399498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c28aac63a56'
down_revision: Union[str, None] = '9adbd83704ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('system_settings', sa.Column('goals_edit_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('system_settings', sa.Column('yearly_goals_final_rating_visible', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('system_settings', sa.Column('project_ratings_visible', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'project_ratings_visible')
    op.drop_column('system_settings', 'yearly_goals_final_rating_visible')
    op.drop_column('system_settings', 'goals_edit_enabled')
    # ### end Alembic commands ###
